services:
  - type: web
    name: uc18-quantity-api
    runtime: docker
    repo: https://github.com/RajSharma2468/QuantityMeasurementApp
    branch: feature/UC18-Authentication
    plan: free
    rootDir: QuantityMeasurementAPILayer
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d75mqtmslomc73du0l70-a.singapore-postgres.render.com;Database=quantitymeasurementdb;Username=uc18_admin;Password=RwyvRacrviYZohgh7VbIirrMMayTXWYn;Port=5432;SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: ThisIsMySuperSecretKeyForJWT1234567890
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient